---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/examples/runner-default"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "terraform"
    directory: "/examples/runner-docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "terraform"
    directory: "/examples/runner-public"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "terraform"
    directory: "/examples/pre-registered"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "terraform"
    directory: "/examples/multi-region"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "terraform"
    directory: "/test/unit/terraform"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: gomod
    directory: /test
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
