---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/examples/runner-default"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
  - package-ecosystem: "terraform"
    directory: "/examples/runner-docker"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
  - package-ecosystem: "terraform"
    directory: "/examples/runner-public"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
  - package-ecosystem: "terraform"
    directory: "/examples/pre-registered"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
  - package-ecosystem: "terraform"
    directory: "/examples/multi-region"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"


  - package-ecosystem: "actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
