---
name: PR opened

on: # yamllint disable-line rule:truthy
  pull_request:
    # GITHUB_TOKEN is readonly and the action will fail for Dependabot
    branches-ignore:
      - 'dependabot/**'
    types:
      - opened
      - locked
      - unlocked

jobs:
  add-welcome-message:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # ratchet:actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // adds a comment to the PR (there is the issue API only which works work PRs too)
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey @${{ github.event.pull_request.user.login }}! \
              \n\n \
              ðŸ‘‹Thank you for your contribution to the project. Please refer to the
              [contribution rules](..//blob/main/CONTRIBUTION.md) for a quick overview of the process. \
              \n\n \
              Make sure that this PR clearly explains: \n \
              - the problem being solved \n \
              - the best way a reviewer and you can test your changes \n \
              \n \
              With submitting this PR you confirm that you hold the rights of the code added and agree \
              that it will published under the [Apache 2.0 license](/blob/main/LICENSE). \
              \n\n \
              This message was generated automatically. You are welcome to \
              [improve it](/blob/main/.github/workflows/new-pr-opened.yml)._'
            })
