---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get app installation token
        uses: npalm/action-app-token@dd4bb16d91ced5659bc618705c96b822c5a42136 # ratchet:npalm/action-app-token@v1.1.0
        id: token
        with:
          appId: ${{ secrets.RELEASER_APP_ID }}
          appPrivateKeyBase64: ${{ secrets.RELEASER_APP_PRIVATE_KEY_BASE64 }}
          appInstallationType: repo
          appInstallationValue: ${{ github.repository }}
      # bootstrap-sha and release-as needs to be removed after first release
      - name: Release
        uses: google-github-actions/release-please-action@a2d8d683f209466ee8c695cd994ae2cf08b1642d # ratchet:google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module
          token: ${{ steps.token.outputs.token }}
          include-v-in-tag: false
          signoff: "Niek Palm <dev.npalm@gmail.com>"
