name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get app installation token
        uses: npalm/action-app-token@dd4bb16d91ced5659bc618705c96b822c5a42136 # ratchet:npalm/action-app-token@v1.1.0
        id: token
        with:
          appId: ${{ secrets.APP_ID }}
          appPrivateKeyBase64: ${{ secrets.APP_PRIVATE_KEY_BASE64 }}
          appInstallationType: repo
          appInstallationValue: ${{ github.repository }}
      # bootstrap-sha and release-as needs to be removed after first release
      - name: Release
        uses: google-github-actions/release-please-action@d3c71f9a0a55385580de793de58da057b3560862 # ratchet:google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module
          token: ${{ steps.token.outputs.token }}
          include-v-in-tag: false
          signoff: "Niek Palm <dev.npalm@gmail.com>"
