name: Verify
on: [pull_request]

jobs:
  verify-module:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: verify
        run: |
          ./ci/bin/install.sh
          ./ci/bin/verify.sh

  verify-examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: verify-examples
        run: |
          ./ci/bin/install.sh
          ./ci/bin/verify-examples.sh
